/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package velmurugan;
import com.itextpdf.text.Paragraph;
import database.databaseconnection;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
/**
 *
 * @author yuvar
 */
public class billing extends javax.swing.JFrame {
    public billing() {
        initComponents();
        fetchNextOrderId();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setVisible(true);
        
    }
    public billing(String furnitureType,String p){
      initComponents();
      ptype.setText(furnitureType);
      pname.setText(p);
       setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

      private void fetchNextOrderId() {
        try {
            Connection con = databaseconnection.getConnection();
            Statement stmt = con.createStatement();
            String query = "SELECT MAX(order_id) AS max_order_id FROM orders";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int nextOrderId = rs.getInt("max_order_id") + 1; 
                jLabel4.setText(String.valueOf(nextOrderId)); 
            } else {
                jLabel4.setText("1"); 
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching next ORDER ID!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        productid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ptype = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        totalamt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BILLING PAGE ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 32, 86, -1));

        jLabel2.setText("ORDER ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 161, -1, -1));

        jLabel3.setText("ORDER DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 161, -1, -1));

        jLabel4.setText("0");
        jLabel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel4FocusGained(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 161, 37, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 158, 104, -1));

        jLabel5.setText("CUSTOMER ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 270, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 267, 37, -1));

        jLabel6.setText("CUSTOMER NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 270, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 267, 104, -1));

        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 270, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 244, -1, -1));

        jLabel8.setText("NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 270, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 267, 106, -1));

        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 37, -1));
        getContentPane().add(productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 37, -1));

        jLabel10.setText("TYPE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 40, -1));
        getContentPane().add(ptype, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 104, -1));

        jLabel11.setText("QUANTITY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 50, -1));

        jLabel12.setText("PRICE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 30, 20));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 90, -1));

        jButton1.setText("SELECT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        jButton3.setText("GENERATE BILL ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, -1, -1));

        jButton4.setText("CLOSE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        jLabel13.setText("PRODUCT NAME");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 100, -1));

        jLabel14.setText("TOTAL");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, -1, -1));

        totalamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalamtActionPerformed(evt);
            }
        });
        getContentPane().add(totalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 430, 100, -1));

        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String cid = jTextField2.getText();
String cname = jTextField3.getText();
String cphone = jTextField4.getText();
String p = productid.getText();
int pid;

try {
    pid = Integer.parseInt(p);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid Product ID! Please enter a numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (cid.isEmpty() && cname.isEmpty() && cphone.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter Customer ID, Name, or Phone!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

Connection con = null;
PreparedStatement customerStmt = null;
PreparedStatement productStmt = null;
ResultSet customerRs = null;
ResultSet productRs = null;

try {
    con = databaseconnection.getConnection();

    // Fetch customer details
    String customerQuery = "SELECT id, name, address, phone FROM customer WHERE ";
    if (!cid.isEmpty()) {
        customerQuery += "id = ?";
    } else if (!cname.isEmpty()) {
        customerQuery += "name = ?";
    } else if (!cphone.isEmpty()) {
        customerQuery += "phone = ?";
    }
    customerStmt = con.prepareStatement(customerQuery);
    if (!cid.isEmpty()) {
        customerStmt.setString(1, cid);
    } else if (!cname.isEmpty()) {
        customerStmt.setString(1, cname);
    } else if (!cphone.isEmpty()) {
        customerStmt.setString(1, cphone);
    }
    customerRs = customerStmt.executeQuery();
    if (customerRs.next()) {
        jTextField2.setText(customerRs.getString("id"));
        jTextField3.setText(customerRs.getString("name"));
        jTextArea1.setText(customerRs.getString("address"));
        jTextField4.setText(customerRs.getString("phone"));
    } else {
        JOptionPane.showMessageDialog(this, "Customer not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Fetch product details
    String productQuery;

if (pid >= 100 && pid < 200) {
    productQuery = "SELECT r_id AS product_id, 1 AS quantity, price AS total_amount FROM racks WHERE r_id = ?";
} else if (pid >= 200 && pid < 500) {
    productQuery = "SELECT chair_id AS product_id, 1 AS quantity, total_price AS total_amount FROM chairs WHERE chair_id = ?";
} else if (pid >= 500 && pid < 700) {
    productQuery = "SELECT t_id AS product_id, 1 AS quantity, totalamt AS total_amount FROM tables WHERE t_id = ?";
} else if (pid >= 700 && pid < 900) {
    productQuery = "SELECT b_id AS product_id, 1 AS quantity, total AS total_amount FROM beds WHERE b_id = ?";
} else {
    JOptionPane.showMessageDialog(this, "Invalid Product ID range!", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Exit as no valid range is matched
}

try {
    productStmt = con.prepareStatement(productQuery);
    productStmt.setString(1, p); // `p` is the product ID entered by the user
    productRs = productStmt.executeQuery();
    if (productRs.next()) {
        // Populate the fields with the fetched product details
        productid.setText(productRs.getString("product_id"));

        if (qty.getText().isEmpty()) {
            qty.setText(productRs.getString("quantity"));
        }
        if (price.getText().isEmpty()) {
            price.setText(productRs.getString("total_amount"));
        }
    } else {
        JOptionPane.showMessageDialog(this, "Product not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error fetching product details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error fetching details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}finally {
    try {
        if (customerRs != null) customerRs.close();
        if (productRs != null) productRs.close();
        if (customerStmt != null) customerStmt.close();
        if (productStmt != null) productStmt.close();
        if (con != null) con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String orderId = jLabel4.getText();
    String orderDateInput = jTextField1.getText(); 
    String customerId = jTextField2.getText();
    String productId = productid.getText();
    String productName = ptype.getText();
    String quantityStr = qty.getText();
    String totalAmountStr = price.getText();

    if (orderId.isEmpty() || orderDateInput.isEmpty() || customerId.isEmpty() ||
        productId.isEmpty() || productName.isEmpty() || quantityStr.isEmpty() || totalAmountStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields before placing the order!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        SimpleDateFormat inputFormat = new SimpleDateFormat("MM/dd/yyyy"); 
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = inputFormat.parse(orderDateInput);
        String orderDate = outputFormat.format(date);
        int quantity = Integer.parseInt(quantityStr);
        double totalAmount = Double.parseDouble(totalAmountStr);
        Connection con = databaseconnection.getConnection();
        String insertOrderQuery = "INSERT INTO orders (order_id, order_date, customer_id, product_id, product_name, quantity,total_amount ) " +
                                  "VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(insertOrderQuery);
        pst.setString(1, orderId);
        pst.setString(2, orderDate); 
        pst.setString(3, customerId);
        pst.setString(4, productId);
        pst.setString(5, productName);
        pst.setInt(6, quantity);
        pst.setDouble(7, totalAmount);
        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "successfully Added ");
            fetchNextOrderId();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to place the order!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        pst.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid date format! Please use MM/DD/YYYY.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
  
        String id = jTextField2.getText();
        String name = jTextField3.getText();
        String number = jTextField4.getText();
        String address = jTextArea1.getText();
        String orderDate = jTextField1.getText();
        String productType = ptype.getText();
        String productName = pname.getText();
        String quantity = qty.getText();
        String pricePerUnit = price.getText();
        String totalAmount = totalamt.getText();
        String path = "C:\\Users\\yuvar\\OneDrive\\Documents\\BILLS\\";

        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();

        try {
            com.itextpdf.text.pdf.PdfWriter.getInstance(doc, new FileOutputStream(path + name + "_" + jLabel4.getText() + ".pdf"));
            doc.open();
            com.itextpdf.text.Paragraph header = new com.itextpdf.text.Paragraph(
                "VELMURUGAN INDUSTRY \nMADURAI, PALANGANATHAM (+91 9994883043)\n\n", 
                com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_BOLD, 16)
            );
            header.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            doc.add(header);

            com.itextpdf.text.Paragraph orderDetails = new com.itextpdf.text.Paragraph(
                "Order ID: ---------------------------------------------------------------" + jLabel4.getText() + 
                "\nOrder Date: -----------------------------------------------------------" + orderDate + 
                "\n\nCUSTOMER DETAILS:----------------------------------------------------" +
                "\nCustomer ID: ----------------------------------------------------------" + id + 
                "\nName: -----------------------------------------------------------------" + name + 
                "\nContact No.: ----------------------------------------------------------" + number + 
                "\nAddress: --------------------------------------------------------------" + address +
                "\n\n"
            );
            doc.add(orderDetails);

            com.itextpdf.text.Paragraph productDetails = new com.itextpdf.text.Paragraph(
                "PRODUCT DETAILS:\n" +
                "--------------------------------------------\n" +
                "Product Type: ------------------------------------------------------------" + productType + 
                "\nProduct Name: ----------------------------------------------------------" + productName + 
                "\nQuantity:--------------------------------------------------------------- " + quantity + 
                "\nPrice per Unit:---------------------------------------------------------" + pricePerUnit +
                "\nTotal Amount: ----------------------------------------------------------" + totalAmount + 
                "\n--------------------------------------------\n\n"
            );
            doc.add(productDetails);

            com.itextpdf.text.Paragraph footer = new com.itextpdf.text.Paragraph(
                "THANK YOU FOR SHOPPING WITH KRK GROUPS!\nVISIT AGAIN !",
                com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_OBLIQUE, 12)
            );
            footer.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            doc.add(footer);

            JOptionPane.showMessageDialog(null, "Bill Generated Successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error while generating bill: " + e.getMessage());
        } finally {
            doc.close();
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void totalamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalamtActionPerformed
        // TODO add your handling code here:i
       
    }//GEN-LAST:event_totalamtActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
         String paid = qty.getText();
        String p = price.getText(); 
        double r =Double.parseDouble(paid);
        double r1 =Double.parseDouble(p);
        Double d = r*r1;
        String tot =String.valueOf(d);
        totalamt.setText(tot);
    }//GEN-LAST:event_qtyActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing("default","default").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productid;
    private javax.swing.JTextField ptype;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField totalamt;
    // End of variables declaration//GEN-END:variables
}
